color: null
description: null
fieldLayouts:
  f408692d-aeda-4199-bbc4-b9e6e5323e1c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-23T15:19:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e0e59d9f-6e59-40c2-997a-eb1d61a3e101
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-07T12:11:15+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 493d156c-cec2-48a1-8873-4db0e47f5d35 # Cikke felépítése
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 645d93c9-c422-41d1-8b2c-dfd8eae834e1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-17T10:08:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: fed5335b-3d92-4ac6-a718-c21c5eab0573 # Képek 
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16c85296-1876-4216-b4d5-102fafaf8320
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-17T13:49:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d11f6ee6-67d9-4ae4-8924-e8dffc44555a # Szöveg
            handle: fKey
            includeInCards: false
            instructions: 'Ha szükséges űrlap adott cikkhez, itt kell megadni az azonosítóját, ami kiolvasható az űrlap pluginból.'
            label: Űrlap
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 567801e9-f3bd-4a03-b0e8-7a5446399c09
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-11-23T16:01:25+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d11f6ee6-67d9-4ae4-8924-e8dffc44555a # Szöveg
            handle: formTitle
            includeInCards: false
            instructions: null
            label: 'Űrlap címe'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7b5475ea-2496-4888-9333-16912c1a8c06
            userCondition: null
            warning: null
            width: 50
        name: Tartalom
        uid: 603cbe38-3f71-4723-9d88-bff71ea7e6ca
        userCondition: null
handle: article
hasTitleField: true
icon: null
name: Cikk
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
