color: null
description: null
fieldLayouts:
  32cee94c-54c1-466a-924e-77238954f3f1:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-07T08:47:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a6bf5104-4ac5-412d-b0c0-233ffa11c1da
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-07T08:56:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8792f1cf-e9e4-4f28-9777-8c5304780529 # Egy kép
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0ec750be-83ed-48c0-b4aa-56c3ac0085db
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-10-07T08:56:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4cb3f0fe-5a28-46e4-aeca-af520ddf4746 # Kapcsoló
            handle: null
            includeInCards: false
            instructions: null
            label: 'Kép bal/jobb'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9068048e-5207-4d70-a037-d6f60948fa59
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-10-07T08:56:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6652c4a0-b521-4514-9e6a-ba6383a6325a # Szöveg doboz
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4bd36ac-58eb-4d56-bcff-ea00f775ad90
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-10-07T08:56:32+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 785c09ff-d241-42d1-b0a7-c985a24a712c # Bejegyzések
            handle: null
            includeInCards: false
            instructions: null
            label: Bővebben
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80238b96-825c-41e1-bf26-1c3226867f6a
            userCondition: null
            warning: null
            width: 100
        name: Tartalom
        uid: 625283f1-195a-46be-814e-90bc5c296299
        userCondition: null
handle: content
hasTitleField: true
icon: subtitles
name: Tartalom
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
