color: null
description: null
fieldLayouts:
  a53c10c1-fc3e-4480-b3ee-24fa81008da8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-23T17:30:29+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 528b4136-fee6-4f42-bc7d-a3b260218c42
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-07T12:40:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1ddf3471-9514-416a-8cdd-cb453f093e39 # Szöveges dokumnetum -  heti menu
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a42c773a-d749-40e5-bae8-628487af6dd5
            userCondition: null
            warning: null
            width: 100
        name: Tartalom
        uid: 3246f1cd-4c7c-4f26-8e8b-edae8440b071
        userCondition: null
handle: default
hasTitleField: true
icon: null
name: Nyitó
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
