altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fb7415a7-f6ff-48f9-86c1-de1f44ac4e48:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-23T15:08:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 780bcfb8-0257-42f9-9e23-8924ce4b9216
            userCondition: null
            warning: null
            width: 100
        name: Tartalom
        uid: 7365a492-12cd-47fa-9c44-ba5af70ae5a2
        userCondition: null
fs: kepek
handle: pictures
name: Képek
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: kepek
transformSubpath: ''
