altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  feb39794-bd56-455b-b1d0-1795e637ac26:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-23T15:09:28+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a73b8323-482d-4727-8b3c-201eebe50e66
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-23T15:11:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d11f6ee6-67d9-4ae4-8924-e8dffc44555a # Szöveg
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6141b94c-1518-4d9d-a898-25f981ac290d
            userCondition: null
            warning: null
            width: 100
        name: Tartalom
        uid: c98ec293-939e-4a45-a458-63800ba8205b
        userCondition: null
fs: sliderPictPlace
handle: sliderPict
name: 'Képváltó képek'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: sliderPictPlace
transformSubpath: ''
