columnSuffix: null
handle: switch
instructions: null
name: Kapcsoló
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
