defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 8bcb174f-c2de-46c2-b796-1394dac78109 # Cikk
handle: articles
maxAuthors: 1
name: Cikkek
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Elsődleges bejegyzés oldal'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0a8824d5-d531-40bc-b0c8-c420edc4449b: # Német
    enabledByDefault: true
    hasUrls: true
    template: articlePost.twig
    uriFormat: 'artikel/{slug}'
  bb5ef826-a820-4982-a272-9ad7d3c5be5a: # parkhedervar
    enabledByDefault: true
    hasUrls: true
    template: articlePost.twig
    uriFormat: 'cikkek/{slug}'
structure:
  maxLevels: null
  uid: 5008f184-22fc-4346-b04e-eb7e8fe13807
type: structure
