defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 02980df4-89da-41dc-9c95-0b95a8764e23 # Menü
handle: menu
maxAuthors: 1
name: Főmenü
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Elsődleges bejegyzés oldal'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0a8824d5-d531-40bc-b0c8-c420edc4449b: # Német
    enabledByDefault: true
    hasUrls: true
    template: fomenu/_entry.twig
    uriFormat: 'fomenu/{slug}'
  bb5ef826-a820-4982-a272-9ad7d3c5be5a: # parkhedervar
    enabledByDefault: true
    hasUrls: true
    template: fomenu/_entry.twig
    uriFormat: 'fomenu/{slug}'
structure:
  maxLevels: null
  uid: fbdcb151-75d1-4523-92a1-834ba722698a
type: structure
