defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: becc6248-77f7-4548-9c0c-9326b0764e28 # HÍr
handle: news
maxAuthors: 1
name: Hírek
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Elsődleges bejegyzés oldal'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0a8824d5-d531-40bc-b0c8-c420edc4449b: # Német
    enabledByDefault: true
    hasUrls: true
    template: _news.twig
    uriFormat: 'news{slug}'
  bb5ef826-a820-4982-a272-9ad7d3c5be5a: # parkhedervar
    enabledByDefault: true
    hasUrls: true
    template: _news.twig
    uriFormat: 'hirek/{slug}'
structure:
  maxLevels: null
  uid: 09790b78-4040-4f01-97d4-2970f3ff37f7
type: structure
