defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3f01429d-2635-4f6a-a7e2-03296a05e255 # Nyitó
handle: nyitolap
maxAuthors: 1
name: Nyitólap
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Elsődleges bejegyzés oldal'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0a8824d5-d531-40bc-b0c8-c420edc4449b: # Német
    enabledByDefault: true
    hasUrls: true
    template: home_parkh.twig
    uriFormat: __home__
  bb5ef826-a820-4982-a272-9ad7d3c5be5a: # parkhedervar
    enabledByDefault: true
    hasUrls: true
    template: home_parkh.twig
    uriFormat: __home__
type: single
